//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviewer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moviereviewerEntities1 : DbContext
    {
        public moviereviewerEntities1()
            : base("name=moviereviewerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<movy> movies { get; set; }
        public virtual DbSet<logincredential> logincredentials { get; set; }
        public virtual DbSet<Moviereview> Moviereviews { get; set; }
    }
}
